In [2]:
import pandas as pd
import numpy as np

# Menyusun baris (skema) menjadi bertingkat
model = ['STL & MLL', 'STL & LDL', 'MTL & MLL', 'MTL & LDL']
balancing = ['Tanpa Balancing', 'Random Undersampling']
splits = ['70:15:15', '80:10:10', '90:5:5']

baris = pd.MultiIndex.from_product(
    [model, balancing, splits],
    names=['Kombinasi Model', 'Balancing', 'Split Data']
)

# Menyusun kolom (skor metrik) secara horizontal
metrik = ['Accuracy', 'Macro F1', 'Precision', 'Recall', 'ROC-AUC', 'MAE']

# Membuat tabel dengan isi awal '-'
data = np.full((len(baris), len(metrik)), '-')
df = pd.DataFrame(data, index=baris, columns=metrik)

#isi untuk stl mll , dengan balancing
df.loc[('MTL & MLL', 'Random Undersampling', '70:15:15'), :] = [0.8471, 0.6889, 0.7041, 0.6773, 0.8490, 0.1903]
df.loc[('MTL & MLL', 'Random Undersampling', '80:10:10'), :] = [0.8106, 0.6970, 0.6743, 0.7556, 0.8546, 0.2145]
df.loc[('MTL & MLL', 'Random Undersampling', '90:5:5'), :] = [0.8259, 0.6843, 0.6819, 0.6867, 0.8412, 0.2043]
df.loc[('MTL & MLL', 'Tanpa Balancing', '70:15:15'), :] = [0.8259, 0.6843, 0.6819, 0.6867, 0.8412, 0.2043]
df.loc[('MTL & MLL', 'Tanpa Balancing', '80:10:10'), :] = [0.8586, 0.6901, 0.7121, 0.6745, 0.8586, 0.1787]
df.loc[('MTL & MLL', 'Tanpa Balancing', '90:5:5'), :] = [0.8465, 0.6188, 0.7175, 0.5966, 0.8443, 0.1786]

df.loc[('MTL & LDL', 'Random Undersampling', '70:15:15'), :] = [0.8507, 0.6620, 0.7086, 0.6394, 0.8422, 0.3670]
df.loc[('MTL & LDL', 'Random Undersampling', '80:10:10'), :] = [0.8645, 0.5962, 0.7565, 0.5762, 0.8465, 0.3539]
df.loc[('MTL & LDL', 'Random Undersampling', '90:5:5'), :] = [0.8456, 0.6862, 0.7113, 0.6696, 0.8331, 0.3867]
df.loc[('MTL & LDL', 'Tanpa Balancing', '70:15:15'), :] = [0.8486, 0.6906, 0.7072, 0.6782, 0.8415, 0.3923]
df.loc[('MTL & LDL', 'Tanpa Balancing', '80:10:10'), :] = [0.8604, 0.6574, 0.7149, 0.6323, 0.8493, 0.3845]
df.loc[('MTL & LDL', 'Tanpa Balancing', '90:5:5'), :] = [0.8393, 0.5836, 0.6872, 0.5701, 0.8325, 0.3873]

df.loc[('STL & LDL', 'Random Undersampling', '70:15:15'), :] = [0.8456, 0.6591, 0.6955, 0.6395, 0.8412, 0.3863]
df.loc[('STL & LDL', 'Random Undersampling', '80:10:10'), :] = [0.8326, 0.6886, 0.6773, 0.7037, 0.8412, 0.3814]
df.loc[('STL & LDL', 'Random Undersampling', '90:5:5'), :] = [0.8312, 0.6639, 0.6807, 0.6521, 0.8316, 0.3862]
df.loc[('STL & LDL', 'Tanpa Balancing', '70:15:15'), :] = [0.8522, 0.6108, 0.7189, 0.5893, 0.8450, 0.3741]
df.loc[('STL & LDL', 'Tanpa Balancing', '80:10:10'), :] = [0.8649, 0.6243, 0.7423, 0.5981, 0.8513, 0.3602]
df.loc[('STL & LDL', 'Tanpa Balancing', '90:5:5'), :] = [0.8411, 0.5072, 0.7346, 0.5244, 0.8181, 0.3561]

df.loc[('STL & MLL', 'Random Undersampling', '70:15:15'), :] = [0.7995, 0.6911, 0.6707, 0.7448, 0.8520, 0.2225]
df.loc[('STL & MLL', 'Random Undersampling', '80:10:10'), :] = [0.8384, 0.7038, 0.6896, 0.7236, 0.8480, 0.1941]
df.loc[('STL & MLL', 'Random Undersampling', '90:5:5'), :] = [0.8115, 0.6750, 0.6658, 0.6871, 0.8400, 0.2105]
df.loc[('STL & MLL', 'Tanpa Balancing', '70:15:15'), :] = [0.8564, 0.6577, 0.7272, 0.6310, 0.8541, 0.1884]
df.loc[('STL & MLL', 'Tanpa Balancing', '80:10:10'), :] = [0.8483, 0.6940, 0.6956, 0.6926, 0.8506, 0.1890]
df.loc[('STL & MLL', 'Tanpa Balancing', '90:5:5'), :] = [0.8393, 0.6462, 0.6923, 0.6258, 0.8479, 0.1831]

# Menampilkan tabel
display(df)

                                                Accuracy Macro F1 Precision  \
Kombinasi Model Balancing            Split Data
STL & MLL       Tanpa Balancing      70:15:15     0.8564   0.6577    0.7272
                                     80:10:10     0.8483    0.694    0.6956
                                     90:5:5       0.8393   0.6462    0.6923
                Random Undersampling 70:15:15     0.7995   0.6911    0.6707
                                     80:10:10     0.8384   0.7038    0.6896
                                     90:5:5       0.8115    0.675    0.6658
STL & LDL       Tanpa Balancing      70:15:15     0.8522   0.6108    0.7189
                                     80:10:10     0.8649   0.6243    0.7423
                                     90:5:5       0.8411   0.5072    0.7346
                Random Undersampling 70:15:15     0.8456   0.6591    0.6955
                                     80:10:10     0.8326   0.6886    0.6773
                                     90:5:5       0.8312   0.6639    0.6807
MTL & MLL       Tanpa Balancing      70:15:15     0.8259   0.6843    0.6819
                                     80:10:10     0.8586   0.6901    0.7121
                                     90:5:5       0.8465   0.6188    0.7175
                Random Undersampling 70:15:15     0.8471   0.6889    0.7041
                                     80:10:10     0.8106    0.697    0.6743
                                     90:5:5       0.8259   0.6843    0.6819
MTL & LDL       Tanpa Balancing      70:15:15     0.8486   0.6906    0.7072
                                     80:10:10     0.8604   0.6574    0.7149
                                     90:5:5       0.8393   0.5836    0.6872
                Random Undersampling 70:15:15     0.8507    0.662    0.7086
                                     80:10:10     0.8645   0.5962    0.7565
                                     90:5:5       0.8456   0.6862    0.7113

                                                 Recall ROC-AUC     MAE
Kombinasi Model Balancing            Split Data
STL & MLL       Tanpa Balancing      70:15:15     0.631  0.8541  0.1884
                                     80:10:10    0.6926  0.8506   0.189
                                     90:5:5      0.6258  0.8479  0.1831
                Random Undersampling 70:15:15    0.7448   0.852  0.2225
                                     80:10:10    0.7236   0.848  0.1941
                                     90:5:5      0.6871    0.84  0.2105
STL & LDL       Tanpa Balancing      70:15:15    0.5893   0.845  0.3741
                                     80:10:10    0.5981  0.8513  0.3602
                                     90:5:5      0.5244  0.8181  0.3561
                Random Undersampling 70:15:15    0.6395  0.8412  0.3863
                                     80:10:10    0.7037  0.8412  0.3814
                                     90:5:5      0.6521  0.8316  0.3862
MTL & MLL       Tanpa Balancing      70:15:15    0.6867  0.8412  0.2043
                                     80:10:10    0.6745  0.8586  0.1787
                                     90:5:5      0.5966  0.8443  0.1786
                Random Undersampling 70:15:15    0.6773   0.849  0.1903
                                     80:10:10    0.7556  0.8546  0.2145
                                     90:5:5      0.6867  0.8412  0.2043
MTL & LDL       Tanpa Balancing      70:15:15    0.6782  0.8415  0.3923
                                     80:10:10    0.6323  0.8493  0.3845
                                     90:5:5      0.5701  0.8325  0.3873
                Random Undersampling 70:15:15    0.6394  0.8422   0.367
                                     80:10:10    0.5762  0.8465  0.3539
                                     90:5:5      0.6696  0.8331  0.3867

pola yang terlihat pada POLAR (TABEL 1): 

1. Aspek Splitting:
    70 30 tengah, 80 20 best, 90 10 worst

2. aspek balancing:
    Jangan gunakan Random Undersampling jika data Anda sedari awal sudah seimbang atau Anda murni mengejar Akurasi. Namun, wajib gunakan Random Undersampling jika data Anda sangat jomplang (imbalanced) dan Anda tidak mau modelnya "buta" terhadap kelas minoritas.
    
    RUS bikin fokus pada acc sama precision
    non rus bikin fokus f1 sama recall 

3. aspek model:
    CONF. MATRIX : mtl unggul cuman dikit, ldl gatau
    MAE : mtl unggul dikit, ldl malah bikin ancur

In [3]:
import pandas as pd
import numpy as np

# Menyusun baris (skema) menjadi bertingkat
model = ['STL & MLL', 'STL & LDL', 'MTL & MLL', 'MTL & LDL']
balancing = ['Tanpa Balancing', 'Random Undersampling']
splits = ['70:15:15', '80:10:10', '90:5:5']

baris = pd.MultiIndex.from_product(
    [model, balancing, splits],
    names=['Kombinasi Model', 'Balancing', 'Split Data']
)

# Menyusun kolom (skor metrik) secara horizontal
metrik = ['Accuracy', 'Macro F1', 'Precision', 'Recall', 'ROC-AUC', 'MAE']

# Membuat tabel dengan isi awal '-'
data = np.full((len(baris), len(metrik)), '-')
df = pd.DataFrame(data, index=baris, columns=metrik)

#isi untuk stl mll , dengan balancing
df.loc[('MTL & MLL', 'Random Undersampling', '70:15:15'), :] = [0.8938, 0.7004, 0.6664, 0.7694, 0.8897, 0.1485]
df.loc[('MTL & MLL', 'Random Undersampling', '80:10:10'), :] = [0.9062, 0.7057, 0.6815, 0.7417, 0.8891, 0.1309]
df.loc[('MTL & MLL', 'Random Undersampling', '90:5:5'), :] = [0.8833, 0.7243, 0.6890, 0.7962, 0.8821, 0.1590]
df.loc[('MTL & MLL', 'Tanpa Balancing', '70:15:15'), :] = [0.9306, 0.6747, 0.7420, 0.6407, 0.8788, 0.0984]
df.loc[('MTL & MLL', 'Tanpa Balancing', '80:10:10'), :] = [0.9354, 0.7310, 0.7689, 0.7041, 0.9009, 0.1083]
df.loc[('MTL & MLL', 'Tanpa Balancing', '90:5:5'), :] = [0.9165, 0.7023, 0.7457, 0.6747, 0.8853, 0.1039]

df.loc[('MTL & LDL', 'Random Undersampling', '70:15:15'), :] = [0.8950, 0.6955, 0.6642, 0.7548, 0.8709, 0.3620]
df.loc[('MTL & LDL', 'Random Undersampling', '80:10:10'), :] = [0.8519, 0.6651, 0.6334, 0.7882, 0.8782, 0.3932]
df.loc[('MTL & LDL', 'Random Undersampling', '90:5:5'), :] = [0.8761, 0.7092, 0.6761, 0.7787, 0.8839, 0.3731]
df.loc[('MTL & LDL', 'Tanpa Balancing', '70:15:15'), :] = [0.9336, 0.6126, 0.8053, 0.5775, 0.8678, 0.3475]
df.loc[('MTL & LDL', 'Tanpa Balancing', '80:10:10'), :] = [0.9313, 0.5686, 0.8474, 0.5476, 0.8730, 0.3024]
df.loc[('MTL & LDL', 'Tanpa Balancing', '90:5:5'), :] = [ 0.9084, 0.5362, 0.6764, 0.5306, 0.8765, 0.3204]

df.loc[('STL & LDL', 'Random Undersampling', '70:15:15'), :] = [0.8501, 0.6606, 0.6298, 0.7859, 0.8686, 0.3859]
df.loc[('STL & LDL', 'Random Undersampling', '80:10:10'), :] = [0.8407, 0.6605, 0.6308, 0.8045, 0.8844, 0.3814]
df.loc[('STL & LDL', 'Random Undersampling', '90:5:5'), :] = [0.8968, 0.7325, 0.7044, 0.7765, 0.8925, 0.3620]
df.loc[('STL & LDL', 'Tanpa Balancing', '70:15:15'), :] = [0.9309, 0.5558, 0.8113, 0.5399, 0.8589, 0.3171]
df.loc[('STL & LDL', 'Tanpa Balancing', '80:10:10'), :] = [0.9363, 0.6663, 0.8133, 0.6204, 0.8775, 0.3334]
df.loc[('STL & LDL', 'Tanpa Balancing', '90:5:5'), :] = [0.9102, 0.6816, 0.7189, 0.6577, 0.8698, 0.3572]

df.loc[('STL & MLL', 'Random Undersampling', '70:15:15'), :] = [0.8728, 0.6790, 0.6446, 0.7753, 0.8896, 0.1524]
df.loc[('STL & MLL', 'Random Undersampling', '80:10:10'), :] = [0.8932, 0.7023, 0.6683, 0.7711, 0.9028, 0.1361]
df.loc[('STL & MLL', 'Random Undersampling', '90:5:5'), :] = [0.8860, 0.7169, 0.6866, 0.7706, 0.8840, 0.1431]
df.loc[('STL & MLL', 'Tanpa Balancing', '70:15:15'), :] = [0.9216, 0.6892, 0.7027, 0.6777, 0.8756, 0.0952]
df.loc[('STL & MLL', 'Tanpa Balancing', '80:10:10'), :] = [0.9165, 0.7101, 0.6998, 0.7220, 0.8879, 0.1021]
df.loc[('STL & MLL', 'Tanpa Balancing', '90:5:5'), :] = [0.9075, 0.6872, 0.7106, 0.6698, 0.8734, 0.0984]

# Menampilkan tabel
display(df)

                                                Accuracy Macro F1 Precision  \
Kombinasi Model Balancing            Split Data
STL & MLL       Tanpa Balancing      70:15:15     0.9216   0.6892    0.7027
                                     80:10:10     0.9165   0.7101    0.6998
                                     90:5:5       0.9075   0.6872    0.7106
                Random Undersampling 70:15:15     0.8728    0.679    0.6446
                                     80:10:10     0.8932   0.7023    0.6683
                                     90:5:5        0.886   0.7169    0.6866
STL & LDL       Tanpa Balancing      70:15:15     0.9309   0.5558    0.8113
                                     80:10:10     0.9363   0.6663    0.8133
                                     90:5:5       0.9102   0.6816    0.7189
                Random Undersampling 70:15:15     0.8501   0.6606    0.6298
                                     80:10:10     0.8407   0.6605    0.6308
                                     90:5:5       0.8968   0.7325    0.7044
MTL & MLL       Tanpa Balancing      70:15:15     0.9306   0.6747     0.742
                                     80:10:10     0.9354    0.731    0.7689
                                     90:5:5       0.9165   0.7023    0.7457
                Random Undersampling 70:15:15     0.8938   0.7004    0.6664
                                     80:10:10     0.9062   0.7057    0.6815
                                     90:5:5       0.8833   0.7243     0.689
MTL & LDL       Tanpa Balancing      70:15:15     0.9336   0.6126    0.8053
                                     80:10:10     0.9313   0.5686    0.8474
                                     90:5:5       0.9084   0.5362    0.6764
                Random Undersampling 70:15:15      0.895   0.6955    0.6642
                                     80:10:10     0.8519   0.6651    0.6334
                                     90:5:5       0.8761   0.7092    0.6761

                                                 Recall ROC-AUC     MAE
Kombinasi Model Balancing            Split Data
STL & MLL       Tanpa Balancing      70:15:15    0.6777  0.8756  0.0952
                                     80:10:10     0.722  0.8879  0.1021
                                     90:5:5      0.6698  0.8734  0.0984
                Random Undersampling 70:15:15    0.7753  0.8896  0.1524
                                     80:10:10    0.7711  0.9028  0.1361
                                     90:5:5      0.7706   0.884  0.1431
STL & LDL       Tanpa Balancing      70:15:15    0.5399  0.8589  0.3171
                                     80:10:10    0.6204  0.8775  0.3334
                                     90:5:5      0.6577  0.8698  0.3572
                Random Undersampling 70:15:15    0.7859  0.8686  0.3859
                                     80:10:10    0.8045  0.8844  0.3814
                                     90:5:5      0.7765  0.8925   0.362
MTL & MLL       Tanpa Balancing      70:15:15    0.6407  0.8788  0.0984
                                     80:10:10    0.7041  0.9009  0.1083
                                     90:5:5      0.6747  0.8853  0.1039
                Random Undersampling 70:15:15    0.7694  0.8897  0.1485
                                     80:10:10    0.7417  0.8891  0.1309
                                     90:5:5      0.7962  0.8821   0.159
MTL & LDL       Tanpa Balancing      70:15:15    0.5775  0.8678  0.3475
                                     80:10:10    0.5476   0.873  0.3024
                                     90:5:5      0.5306  0.8765  0.3204
                Random Undersampling 70:15:15    0.7548  0.8709   0.362
                                     80:10:10    0.7882  0.8782  0.3932
                                     90:5:5      0.7787  0.8839  0.3731

pola yang terlihat pada POLAR (TABEL 1): 
ASPEK SPLITTING:
-AKURASI
1. 5 DARI 8 terbesar adalah 80 10 10
2. 5 dari 8 terkecil adalah 90 10 10 


70:15:15


80:10:10 memiliki kecenderungan menjadi rasio yang terbaik, karena metrik tertinggi rata-rata ada di aspek ini.

90:10:10